/**
 * Reads skill markdown files from the shared skills directory,
 * strips YAML frontmatter, and generates a TypeScript module
 * with string constants for each skill's content.
 *
 * Run: bun scripts/generate-prompts.ts
 * Output: src/prompts/skills-content.ts
 */

import { readFileSync, writeFileSync, existsSync } from "fs"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const SKILLS_DIR = resolve(__dirname, "../../../skills")
const OUTPUT_FILE = resolve(__dirname, "../src/prompts/skills-content.ts")

// Skill sources: variable name → file path (relative to skills dir)
const SKILL_SOURCES: Record<string, string> = {
  USING_ALLYE: "using-allye/SKILL.md",
  HANDOVER_PROTOCOL: "handover-protocol/SKILL.md",
  SANDBOX: "sandbox/SKILL.md",
  PRODUCT_PLANNING: "product-planning/SKILL.md",
  TECHNICAL_PLANNING: "technical-planning/SKILL.md",
  ORCHESTRATOR: "orchestrator/SKILL.md",
  TECHNICAL_DEVELOPMENT: "execution/SKILL.md",
  TECHNICAL_REVIEW: "review/SKILL.md",
  TECHNICAL_DELIVERY: "delivery/SKILL.md",
  MEMORY_PROTOCOL: "memory-protocol/SKILL.md",
  TDD_WORKFLOW: "tdd-workflow/SKILL.md",
  BOARD_PROGRESSION: "board-progression/SKILL.md",
  TOOLS_QUICKREF: "tools-quickref/SKILL.md",
}

function stripFrontmatter(content: string): string {
  const match = content.match(/^---\n[\s\S]*?\n---\n/)
  if (match) {
    return content.slice(match[0].length).trim()
  }
  return content.trim()
}

/**
 * Removes content wrapped in <!-- opencode-exclude:start --> ... <!-- opencode-exclude:end -->
 * markers. Skill files use these to fence off Claude-Code-only instructions
 * (e.g. dispatching the `executor` subagent via the Agent tool) that must not
 * be embedded into OpenCode agent prompts, where those capabilities don't exist.
 */
function stripOpencodeExcluded(content: string, sourcePath: string): string {
  const stripped = content.replace(
    /<!--\s*opencode-exclude:start\s*-->[\s\S]*?<!--\s*opencode-exclude:end\s*-->/g,
    ""
  )
  if (/<!--\s*opencode-exclude:(start|end)\s*-->/.test(stripped)) {
    throw new Error(
      `Unbalanced opencode-exclude markers in ${sourcePath} — every start marker needs a matching end marker.`
    )
  }
  // Collapse blank-line runs left behind by removed blocks.
  return stripped.replace(/\n{3,}/g, "\n\n").trim()
}

function escapeTemplate(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$")
}

function main() {
  const lines: string[] = [
    "// AUTO-GENERATED — Do not edit manually.",
    "// Generated by: bun scripts/generate-prompts.ts",
    `// Source: ${SKILLS_DIR}`,
    `// Generated at: ${new Date().toISOString()}`,
    "",
  ]

  for (const [varName, relativePath] of Object.entries(SKILL_SOURCES)) {
    const fullPath = resolve(SKILLS_DIR, relativePath)

    if (!existsSync(fullPath)) {
      console.warn(`⚠ Skill not found: ${relativePath} — skipping`)
      lines.push(`export const ${varName} = ""`)
      lines.push("")
      continue
    }

    const raw = readFileSync(fullPath, "utf-8")
    const content = stripOpencodeExcluded(stripFrontmatter(raw), relativePath)
    const escaped = escapeTemplate(content)

    lines.push(`export const ${varName} = \`${escaped}\``)
    lines.push("")

    console.log(`✓ ${varName} (${content.length} chars)`)
  }

  writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8")
  console.log(`\n→ Generated: ${OUTPUT_FILE}`)
}

main()
