/**
 * Build-time preparation. Copies the repository's single sources into the
 * package so the published tarball is self-contained:
 * - bootstrap/allye.md      -> src/bootstrap.generated.ts (string export)
 * - skills/bridge*          -> skills/ (registered with OpenCode at runtime)
 * - agents/bridge-*.md      -> src/agents.generated.ts (crew subagents)
 * All outputs are gitignored; edit the repository sources, never the copies.
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const pkg = resolve(import.meta.dir, "..")
const root = resolve(pkg, "../..")

const bootstrapPath = join(root, "bootstrap", "allye.md")
if (!existsSync(bootstrapPath)) throw new Error(`Shared bootstrap not found at ${bootstrapPath}`)
const bootstrap = readFileSync(bootstrapPath, "utf8")
writeFileSync(
  join(pkg, "src", "bootstrap.generated.ts"),
  `// Generated by scripts/prepare.ts from bootstrap/allye.md. Do not edit.\nexport const BOOTSTRAP = ${JSON.stringify(bootstrap)}\n`,
)

const skillsOut = join(pkg, "skills")
rmSync(skillsOut, { recursive: true, force: true })
mkdirSync(skillsOut, { recursive: true })
const bridgeSkills = readdirSync(join(root, "skills")).filter((name) => name === "bridge" || name.startsWith("bridge-"))
if (bridgeSkills.length === 0) throw new Error("No Bridge skills found under skills/")
for (const name of bridgeSkills) cpSync(join(root, "skills", name), join(skillsOut, name), { recursive: true })

// agents/bridge-*.md -> src/agents.generated.ts (native crew subagents).
// The Claude Code agent files are the single source: name, description, tool
// allowlist and body. index.ts maps the allowlist to OpenCode permissions.
const agentsDir = join(root, "agents")
const agents = readdirSync(agentsDir)
  .filter((file) => file.startsWith("bridge-") && file.endsWith(".md"))
  .sort()
  .map((file) => {
    const text = readFileSync(join(agentsDir, file), "utf8")
    const match = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
    if (!match) throw new Error(`agents/${file}: missing frontmatter`)
    const field = (key: string) => match[1].match(new RegExp(`^${key}: (.*)$`, "m"))?.[1]
    const name = field("name")
    const description = field("description")
    const tools = field("tools")?.split(",").map((tool) => tool.trim()).filter(Boolean)
    if (name !== file.replace(/\.md$/, "") || !description || !tools?.length) {
      throw new Error(`agents/${file}: name, description and tools are required`)
    }
    if (!bridgeSkills.includes(name)) throw new Error(`agents/${file}: no matching skills/${name}`)
    const body = match[2].trim()
    // index.ts rewrites these two phrases for OpenCode; fail the build if they drift.
    for (const phrase of [`with the Skill tool (name \`allye:${name}\`)`, `\`../skills/${name}/SKILL.md\`, relative to this agent file`]) {
      if (!body.includes(phrase)) throw new Error(`agents/${file}: body must contain: ${phrase}`)
    }
    return { name, description, tools, body }
  })
if (agents.length === 0) throw new Error("No crew agents found under agents/")
writeFileSync(
  join(pkg, "src", "agents.generated.ts"),
  `// Generated by scripts/prepare.ts from agents/bridge-*.md. Do not edit.\nexport const AGENTS: ReadonlyArray<{ name: string; description: string; tools: string[]; body: string }> = ${JSON.stringify(agents, null, 2)}\n`,
)

console.log(`prepared bootstrap (${bootstrap.length} chars), skills: ${bridgeSkills.join(", ")}; agents: ${agents.length}`)
