/**
 * Build-time preparation. Copies the repository's single sources into the
 * package so the published tarball is self-contained:
 * - bootstrap/allye.md      -> src/bootstrap.generated.ts (string export)
 * - skills/bridge*          -> skills/ (registered with OpenCode at runtime)
 * Both outputs are gitignored; edit the repository sources, never the copies.
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const pkg = resolve(import.meta.dir, "..")
const root = resolve(pkg, "../..")

const bootstrapPath = join(root, "bootstrap", "allye.md")
if (!existsSync(bootstrapPath)) throw new Error(`Shared bootstrap not found at ${bootstrapPath}`)
const bootstrap = readFileSync(bootstrapPath, "utf8")
writeFileSync(
  join(pkg, "src", "bootstrap.generated.ts"),
  `// Generated by scripts/prepare.ts from bootstrap/allye.md. Do not edit.\nexport const BOOTSTRAP = ${JSON.stringify(bootstrap)}\n`,
)

const skillsOut = join(pkg, "skills")
rmSync(skillsOut, { recursive: true, force: true })
mkdirSync(skillsOut, { recursive: true })
const bridgeSkills = readdirSync(join(root, "skills")).filter((name) => name === "bridge" || name.startsWith("bridge-"))
if (bridgeSkills.length === 0) throw new Error("No Bridge skills found under skills/")
for (const name of bridgeSkills) cpSync(join(root, "skills", name), join(skillsOut, name), { recursive: true })

console.log(`prepared bootstrap (${bootstrap.length} chars) and skills: ${bridgeSkills.join(", ")}`)
